- from: base
  test: ":(){ :|: & };:"
  method: Contains
  enable: true
  description: "This short line defines a shell function that creates new copies of itself.\nThe process continually replicates itself, and its copies continually replicate themselves, quickly taking up all your CPU time and memory.\nThis can cause your computer to freeze. It’s basically a denial-of-service attack."
- from: base
  test: \s*crontab\s+-r
  method: Regex
  enable: true
  description: "You are going to remove your entire table of cron tasks."
- from: base
  test: \s*history.*.[|].*.(bash|sh)
  method: Regex
  enable: true
  description: "You are going to executes every command from the command log that you have already executed."
- from: base
  test: (\.*)reboot[^."']*{0,}
  method: Regex
  enable: true
  description: "You are going to reboot your machine."
- from: base
  test: (\.*)shutdown[^."']*{0,}
  method: Regex
  enable: true
  description: "You are going to shutdown your machine."
