- from: database
  test: (?i)DROP\s+DATABASE
  description: "Dropping a database will permanently delete all its data."
  id: database:drop_database
  severity: Critical
- from: database
  test: (?i)DROP\s+TABLE
  description: "Dropping a table will permanently delete all its data."
  id: database:drop_table
  severity: Critical
- from: database
  test: (?i)TRUNCATE\s+TABLE
  description: "Truncating a table will delete all rows permanently."
  id: database:truncate_table
  severity: Critical
- from: database
  test: (?i)DELETE\s+FROM\s+\w+\s*;?\s*$
  description: "DELETE without a WHERE clause will delete all rows in the table."
  id: database:delete_all_rows
  severity: Critical
  filters:
    - type: NotContains
      value: "WHERE"
    - type: NotContains
      value: "where"
  alternative: "DELETE FROM <table> WHERE <condition>"
  alternative_info: "Always include a WHERE clause to limit which rows are deleted."
- from: database
  test: (?i)UPDATE\s+\w+\s+SET\s+.*(?:;|\s*$)
  description: "UPDATE without a WHERE clause will modify all rows in the table."
  id: database:update_all_rows
  severity: High
  filters:
    - type: NotContains
      value: "WHERE"
    - type: NotContains
      value: "where"
