---
challenge: Math
includes:
  - base
  - fs
  - git
version: 0.1.6
checks:
  - test: "rm\\s*(-r|-fr|-rf)\\s*(\\*|\\.\\z|\\./\\z|\\.\\.|/)"
    method: Regex
    enable: true
    description: You are going to delete everything in the path.
    from: fs
    challenge: Default
    filters: {}
  - test: mv+.*/dev/null
    method: Regex
    enable: true
    description: The files will be discarded and destroyed.
    from: fs
    challenge: Default
    filters: {}
  - test: ".*>(.*)"
    method: Regex
    enable: true
    description: The above command is used to flush the content of a file.
    from: fs
    challenge: Default
    filters:
      IsFileExists: "1"
  - test: "chmod\\s*(-R)\\s+[0-9]{1,}\\s*(\\*|\\.\\z|\\./\\z|\\.\\.|\\.|/)"
    method: Regex
    enable: true
    description: Change permission to all root files can brake your some thinks like SSH keys.
    from: fs
    challenge: Default
    filters: {}
  - test: "\\s*find\\s*-delete"
    method: Regex
    enable: true
    description: Did you -delete flag in the wrong order? find -delete going to delete all the file under your current path.
    from: fs
    challenge: Default
    filters: {}
  - test: git reset
    method: Contains
    enable: true
    description: This command going to reset all your local changes.
    from: git
    challenge: Default
    filters: {}
  - test: ":(){ :|: & };:"
    method: Contains
    enable: true
    description: "This short line defines a shell function that creates new copies of itself.\nThe process continually replicates itself, and its copies continually replicate themselves, quickly taking up all your CPU time and memory.\nThis can cause your computer to freeze. It’s basically a denial-of-service attack."
    from: base
    challenge: Default
    filters: {}
  - test: "\\s*history.*.[|].*.(bash|sh)"
    method: Regex
    enable: true
    description: You are going to executes every command from the command log that you have already executed.
    from: base
    challenge: Default
    filters: {}
  - test: "(\\.*)reboot[^.\"']*{0,}"
    method: Regex
    enable: true
    description: You are going to reboot your machine.
    from: base
    challenge: Default
    filters: {}
  - test: "(\\.*)shutdown[^.\"']*{0,}"
    method: Regex
    enable: true
    description: You are going to shutdown your machine.
    from: base
    challenge: Default
    filters: {}
